const SCRIPT_URL="https://script.google.com/macros/s/AKfycbzW977LTZkwhYL5oXAaTbixYbCVHOtIGyMFz80uZw7HNpKNVdHtRUmooUm0941D1LZR/exec";
const WHATSAPP_NUMBER="525535690278";
const EVENT_NAME="Atelier N8 - Lanzamiento Colección 01";
const EVENT_DATE=new Date("2026-10-08T19:30:00-06:00");
const DRAFT_KEY="invyra_corporate_legacy_rsvp";
let experienceOpened=false;
let resumeMusicOnReturn=false;

document.addEventListener("DOMContentLoaded",()=>{
  const splash=document.getElementById("splash"),music=document.getElementById("bg-music"),form=document.getElementById("rsvpForm");
  setPersonalization();restoreDraft(form);updateAttendance(form);initCountdown();initReveal();
  document.getElementById("openExperience")?.addEventListener("click",()=>{splash?.classList.add("is-opening");document.body.classList.remove("is-locked");experienceOpened=true;playMusicWithFade(music);window.setTimeout(()=>splash?.remove(),950);});
  initAudioLifecycle(music);
  form?.addEventListener("input",()=>saveDraft(form));form?.addEventListener("change",()=>{updateAttendance(form);saveDraft(form);});form?.addEventListener("submit",event=>submitRsvp(event,form));document.getElementById("closeModal")?.addEventListener("click",closeModal);
});

function playMusicWithFade(music){if(!music)return;music.volume=0;music.play().then(()=>{resumeMusicOnReturn=true;const startedAt=performance.now();const fade=now=>{const progress=Math.min((now-startedAt)/1900,1);music.volume=.32*progress;if(progress<1&&!music.paused)requestAnimationFrame(fade);};requestAnimationFrame(fade);}).catch(error=>console.log("Interacción requerida para reproducir audio:",error));}
function initAudioLifecycle(music){if(!music)return;const pauseForBackground=()=>{if(!experienceOpened)return;if(!music.paused)resumeMusicOnReturn=true;music.pause();};const resumeAfterReturn=()=>{if(!experienceOpened||!resumeMusicOnReturn||document.hidden)return;music.play().catch(error=>console.log("No se pudo reanudar el audio:",error));};document.addEventListener("visibilitychange",()=>document.hidden?pauseForBackground():resumeAfterReturn());window.addEventListener("pagehide",pauseForBackground);window.addEventListener("pageshow",resumeAfterReturn);}

function setPersonalization(){const guest=new URLSearchParams(location.search).get("invitado")?.trim();if(!guest)return;const safe=guest.slice(0,70);document.getElementById("guestWelcome").textContent=`Acceso preparado para ${safe}`;document.getElementById("heroGuest").textContent=safe;document.getElementById("digitalGuest").textContent=safe;const input=document.getElementById("guestName");if(input&&!input.value)input.value=safe;}
function initCountdown(){const update=()=>{const remaining=Math.max(0,EVENT_DATE-Date.now());const values={days:Math.floor(remaining/86400000),hours:Math.floor((remaining/3600000)%24),minutes:Math.floor((remaining/60000)%60),seconds:Math.floor((remaining/1000)%60)};Object.entries(values).forEach(([unit,value])=>{const node=document.querySelector(`[data-unit="${unit}"]`);if(node)node.textContent=String(value).padStart(2,"0");});};update();setInterval(update,1000);}
function initReveal(){const elements=document.querySelectorAll(".reveal");if(!("IntersectionObserver" in window))return elements.forEach(element=>element.classList.add("is-visible"));const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add("is-visible");observer.unobserve(entry.target);}}),{threshold:.1});elements.forEach(element=>observer.observe(element));}
function updateAttendance(form){const attending=form?.querySelector('input[name="attendance"]:checked')?.value==="Asistiré";const fields=document.getElementById("attendingFields");if(fields)fields.hidden=!attending;fields?.querySelectorAll("select,input").forEach(field=>field.disabled=!attending);}

async function submitRsvp(event,form){event.preventDefault();const status=document.getElementById("formStatus"),button=document.getElementById("submitButton"),name=document.getElementById("guestName")?.value.trim(),company=document.getElementById("company")?.value.trim()||"No indicada",attendance=form.querySelector('input[name="attendance"]:checked')?.value||"Sin respuesta",attending=attendance==="Asistiré",access=attending?document.getElementById("accessType")?.value:"No aplica",count=attending?document.getElementById("guestCount")?.value:"No aplica",menu=attending?document.getElementById("menuChoice")?.value:"No aplica",message=document.getElementById("guestMessage")?.value.trim()||"Sin mensaje";
  if(!name){if(status)status.textContent="Escribe tu nombre para continuar.";document.getElementById("guestName")?.focus();return;}
  button.disabled=true;button.textContent="Registrando acceso...";if(status)status.textContent="Validando invitación...";
  try{const response=await sendJsonp({nombre:name,asistencia:attendance,mensaje:`Empresa: ${company} · ${message}`,evento:EVENT_NAME,detalleAsistencia:`${access} · ${count}`,menu});if(response?.status==="duplicate"){showModal("Acceso ya registrado","Ya existe una respuesta asociada a este nombre. Escríbenos si necesitas modificarla.");return;}if(response?.status!=="success")throw new Error(response?.message||"Respuesta inesperada");localStorage.removeItem(DRAFT_KEY);showModal("Acceso confirmado","Tu asistencia y preferencias quedaron registradas correctamente.");const text=["Hola, confirmo mi acceso al lanzamiento de Atelier N8.","",`Nombre: ${name}`,`Empresa: ${company}`,`Asistencia: ${attendance}`,attending?`Tipo de acceso: ${access}`:"",attending?`Acompañantes: ${count}`:"",attending?`Preferencia gastronómica: ${menu}`:"",`Mensaje: ${message}`].filter(Boolean).join("\n");setTimeout(()=>window.open(`https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(text)}`,"_blank","noopener,noreferrer"),900);form.reset();updateAttendance(form);}catch(error){console.error(error);showModal("No pudimos registrar","La conexión tardó demasiado. Tu información permanece guardada para intentarlo nuevamente.");}finally{button.disabled=false;button.textContent="Registrar asistencia";if(status)status.textContent="";}}

function sendJsonp(data){return new Promise((resolve,reject)=>{const callback=`invyraCorporateCallback_${Date.now()}_${Math.floor(Math.random()*10000)}`,script=document.createElement("script"),timeout=setTimeout(()=>{cleanup();reject(new Error("Tiempo agotado"));},12000);function cleanup(){clearTimeout(timeout);script.remove();try{delete window[callback];}catch(_){window[callback]=undefined;}}window[callback]=response=>{cleanup();resolve(response||{status:"error"});};script.onerror=()=>{cleanup();reject(new Error("Sin conexión"));};script.src=`${SCRIPT_URL}?${new URLSearchParams({callback,...data})}`;document.body.appendChild(script);});}
function saveDraft(form){if(!form)return;try{localStorage.setItem(DRAFT_KEY,JSON.stringify(Object.fromEntries(new FormData(form).entries())));}catch(_){}}
function restoreDraft(form){if(!form)return;try{const data=JSON.parse(localStorage.getItem(DRAFT_KEY)||"{}");Object.entries(data).forEach(([name,value])=>{const field=form.querySelector(`[name="${CSS.escape(name)}"]`);if(!field)return;if(field.type==="radio"){const option=form.querySelector(`[name="${CSS.escape(name)}"][value="${CSS.escape(value)}"]`);if(option)option.checked=true;}else field.value=value;});}catch(_){}}
function showModal(title,message){document.getElementById("modalTitle").textContent=title;document.getElementById("modalMessage").textContent=message;document.getElementById("responseModal").hidden=false;}function closeModal(){document.getElementById("responseModal").hidden=true;}
